FROM node:22-alpine AS build

WORKDIR /app

ARG PUBLIC_SITE_URL=https://rmfrt.com
ARG PUBLIC_NOINDEX=true
ARG PUBLIC_UMAMI_SCRIPT_URL=
ARG PUBLIC_UMAMI_WEBSITE_ID=
ARG PUBLIC_UMAMI_DOMAINS=

ENV PUBLIC_SITE_URL=$PUBLIC_SITE_URL
ENV PUBLIC_NOINDEX=$PUBLIC_NOINDEX
ENV PUBLIC_UMAMI_SCRIPT_URL=$PUBLIC_UMAMI_SCRIPT_URL
ENV PUBLIC_UMAMI_WEBSITE_ID=$PUBLIC_UMAMI_WEBSITE_ID
ENV PUBLIC_UMAMI_DOMAINS=$PUBLIC_UMAMI_DOMAINS

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.29-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html/

EXPOSE 3000
